name: Pipeline
on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Clona o repo
        uses: actions/checkout@v6
      
      - name: Instala o python
        uses: actions/setup-python@v6 
        with:
          python-version: '3.14'

      - name: Instala as dependências
        run: pip install -r requirements.txt
