name: Pipeline
on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Clona o repo
        uses: actions/checkout@v6.0.2
      
      - name: Instala o python
        uses: actions/setup-python@v6.2.0 
        with:
          python-version: '3.14'
