name: Pipeline
on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Clona o repo
        uses: actions/checkout@v6.0.2
      
      - name: Lista os arquivos
        run: echo $(ls)
